version: '3.8'

services:
  htr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: htr-application
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - TRANSFORMERS_CACHE=/app/models
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G